name = "remix"

workers_dev = true
main = "./build/index.js"
compatibility_date = "2023-03-26"
compatibility_flags = ["nodejs_compat"]

# https://developers.cloudflare.com/workers/platform/compatibility-dates/#streams-constructors
# compatibility_flags = ["streams_enable_constructors"]
# [env.production.vars]
# NODE_VERSION = "18.15.0"

[site]
bucket = "./public"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "logs-bucket"
preview_bucket_name = "preview-logs-bucket"

# [build]
#   command = "npm run build"
